version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deputy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deputy || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - deputy-net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - deputy-net

  api:
    build:
      context: ..
      dockerfile: Presentation/Dockerfile
    container_name: deputy-api
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: Host=postgres;Port=5432;Database=deputy;Username=postgres;Password=postgres
      MINIO_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: deputy-files
      TELEGRAM_BOT_TOKEN: "8199749012:AAHpLWXWRbOZllvggRBtWC76RGItI9-xWQ4"
      TELEGRAM_CHAT_ID: ""
      JWT_KEY: "AAAAB3NzaC1yc2EAAAABJQAAACEA3N1qw1YmAimBUVDFVgHdDulVCiQuBtCaDYQEf5FGMhM"
      Jwt__Issuer: deputyapp
      Jwt__Audience: deputyapp
      Telegram__UseWebhook: false
      Telegram__WebhookUrl: https://irit-rtf-ep.ru/api/telegram
      INTERNAL_API: http://telegram-api/api/telegram
    ports:
      - "6000:80"
    networks:
      - deputy-net

  telegram-api:
    build:
      context: ..
      dockerfile: TelegramAPI/Dockerfile
    container_name: telegram-api
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: Host=postgres;Port=5432;Database=deputy;Username=postgres;Password=postgres
      TELEGRAM_BOT_TOKEN: "8199749012:AAHpLWXWRbOZllvggRBtWC76RGItI9-xWQ4"
      TELEGRAM_CHAT_ID: ""
      Telegram__UseWebhook: false
      Telegram__WebhookUrl: https://irit-rtf-ep.ru/api/telegram
      API_ADDRESS: http://deputy-api/api/internal
    ports:
      - "7000:80"
    networks:
      - deputy-net

volumes:
  pgdata:
  miniodata:

networks:
  deputy-net:
